### ISSUE TITLE
gpg: signing failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by mcdonnell-john** [samuelmeuli/action-maven-publish#1]
**Description**
Getting the following error when attempting to execute this action:
`gpg: signing failed: Inappropriate ioctl for device`

**Steps to reproduce**
I setup this project:
https://github.com/mcdonnell-john/nb-google-java-code-formatter-plugin, which has the following release.yml GitHub action:

```
name: Release
# Run workflow only on pushes to a tag starting with v
on:
  push:
    tags:        
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Release to Central Repository
        uses: samuelmeuli/action-maven-publish@master
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          ossrh_username: ${{ secrets.ossrh_username }}
          ossrh_password: ${{ secrets.ossrh_password }}
```

When this runs, I am getting that error, I have included the logs from that section of the action if that helps:
[4_Release to Central Repository.txt](https://github.com/samuelmeuli/action-maven-publish/files/3866328/4_Release.to.Central.Repository.txt)

**Comment by samuelmeuli** [comment]
Try configuring the GPG plugin like this:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <version>1.6</version>
    <executions>
        <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
                <goal>sign</goal>
            </goals>
            <configuration>
                <!-- Prevent `gpg` from using pinentry programs -->
                <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                </gpgArguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by mcdonnell-john** [comment]
Perfect, thanks @samuelmeuli

**Comment by tomsun28** [comment]
@samuelmeuli hi, thanks for this project
i config gpg like above [pom.xm](https://github.com/tomsun28/sureness/blob/master/core/pom.xml)   
and config action lisk this:

````
# deploy it to maven central

name: Maven Package

on:
  release:
    types: [published, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        directory: core/
        server_id: tom
````

but the error gpg: signing failed: Inappropriate ioctl for device also happen

````
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.358 s
[INFO] Finished at: 2020-08-31T03:07:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project sureness-core: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
child_process.js:660
    throw err;
    ^
Error: Command failed: mvn clean deploy --batch-mode --activate-profiles deploy --settings /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.4.0/settings.xml 
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.4.0/index.js:23:9)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.4.0/index.js:83:2)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.4.0/index.js:89:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2678,
  stdout: null,
  stderr: null
}
````

**Comment by tomsun28** [comment]
it is ok, i forget add this as you note in readme
````
                                <configuration>
                                    <!-- Prevent `gpg` from using pinentry programs -->
                                    <gpgArguments>
                                        <arg>--pinentry-mode</arg>
                                        <arg>loopback</arg>
                                    </gpgArguments>
                                </configuration>
````
