### ISSUE TITLE
"gpg: signing failed: No such file or directory"

### ISSUE THREAD

**Issue by julie-sullivan** [samuelmeuli/action-maven-publish#3]
I set my four secrets, but I got this error:

```
gpg: signing failed: No such file or directory
gpg: signing failed: No such file or directory
```

```
child_process.js:655
    throw err;
    ^

Error: Command failed: mvn clean deploy --batch-mode --activate-profiles deploy --settings /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/settings.xml $INPUT_MAVEN_ARGS
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/index.js:16:20)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/index.js:32:2)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/index.js:37:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3465,
  stdout: null,
  stderr: null
}
```

Any ideas what I did wrong? Thanks!!!!!

**Comment by samuelmeuli** [comment]
Hi Julie,

I've made a few improvements to the action and released `v1.1`. It will now check whether all required input variables have been defined. Could you please check whether there's a different log output with the new version?

**Comment by julie-sullivan** [comment]
Thanks so much! Yes, this is a fun one:

```
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/jgit/org.eclipse.jgit/4.0.0.201506090130-r/org.eclipse.jgit-4.0.0.201506090130-r.jar (2.1 MB at 5.9 MB/s)
java.lang.RuntimeException: Unable to find commits until some tag
	at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag(JGitCommon.java:286)
	at pl.project13.jgit.DescribeCommand.call(DescribeCommand.java:298)
	at pl.project13.maven.git.JGitProvider.getGitDescribe(JGitProvider.java:234)
	at pl.project13.maven.git.JGitProvider.getGitDescribe(JGitProvider.java:125)
	at pl.project13.maven.git.GitDataProvider.maybePutGitDescribe(GitDataProvider.java:148)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:113)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:637)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:608)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:423)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jgit.errors.RevWalkException: Walk failure.
	at org.eclipse.jgit.revwalk.RevWalk.iterator(RevWalk.java:1325)
	at pl.project13.jgit.JGitCommon.findCommitsUntilSomeTag(JGitCommon.java:274)
	... 21 more
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit cecfccb3cf45f0bc331b578a66df13620166040b
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:147)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:903)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:150)
	at org.eclipse.jgit.revwalk.PendingGenerator.next(PendingGenerator.java:147)
	at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:184)
	at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:435)
	at org.eclipse.jgit.revwalk.RevWalk.iterator(RevWalk.java:1323)
	... 22 more

...
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project cellbase-core: Could not complete Mojo execution...: Unable to find commits until some tag: Walk failure. Missing commit cecfccb3cf45f0bc331b578a66df13620166040b -> [Help 1]
[ERROR] 
```

Does that help you at all?

**Comment by julie-sullivan** [comment]
thanks so much for looking at this! Same error I think:

```

Error: Command failed: mvn clean deploy --batch-mode --activate-profiles deploy --settings /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.1.0/settings.xml 
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.1.0/index.js:24:27)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.1.0/index.js:62:2)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1.1.0/index.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3756,
  stdout: null,
  stderr: null
}
##[error]Node run failed with exit code 1
```

**Comment by julie-sullivan** [comment]
```
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project cellbase: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
child_process.js:655
    throw err;
    ^
```

**Comment by samuelmeuli** [comment]
Have you configured the GPG plugin like in [this guide](https://github.com/samuelmeuli/action-maven-publish/blob/master/docs/deployment-setup.md)?

**Comment by julie-sullivan** [comment]
yes I have!

https://github.com/opencb/cellbase/blob/next/pom.xml

Do you think that's the error?

**Comment by samuelmeuli** [comment]
I think this part is missing in your POM:

```xml
<configuration>
  <!-- Prevent `gpg` from using pinentry programs -->
  <gpgArguments>
    <arg>--pinentry-mode</arg>
    <arg>loopback</arg>
  </gpgArguments>
</configuration>
```

**Comment by julie-sullivan** [comment]
Thanks!! That was the problem. Apologies, user error. 

And thanks for this great github action, this has made my life so much easier! :)
