### ISSUE TITLE
Issues from version 1.3

### ISSUE THREAD

**Issue by imedina** [samuelmeuli/action-maven-publish#7]
Hi,

Many thanks for this GitHub Action plugin!  I have been using it for several days and it was working great.

But since version 1.3 released yesterday (4/1/2020) it is not working anymore, it seems to be related to _child_process_ library. See this screenshot and the logs below. I hope this helps, thanks!

![image](https://user-images.githubusercontent.com/1427327/71784671-a6c67500-2fed-11ea-8864-9e5dfa014f70.png)

Logs:

2020-01-04T17:14:29.8921914Z [INFO] ------------------------------------------------------------------------
2020-01-04T17:14:29.8922706Z [INFO] BUILD SUCCESS
2020-01-04T17:14:29.8923622Z [INFO] ------------------------------------------------------------------------
2020-01-04T17:14:29.8924411Z [INFO] Total time:  55.498 s (Wall Clock)
2020-01-04T17:14:29.8925288Z [INFO] Finished at: 2020-01-04T17:14:29Z
2020-01-04T17:14:29.8927263Z [INFO] ------------------------------------------------------------------------
2020-01-04T17:14:29.9515077Z ##[group]Run samuelmeuli/action-maven-publish@v1
2020-01-04T17:14:29.9515808Z with:
2020-01-04T17:14:29.9517365Z   nexus_username: ***
2020-01-04T17:14:29.9518267Z   nexus_password: ***
2020-01-04T17:14:29.9526540Z   gpg_private_key: ***

2020-01-04T17:14:29.9527249Z   gpg_passphrase: ***
2020-01-04T17:14:29.9527893Z   maven_args: -DskipTests
2020-01-04T17:14:29.9528535Z   server_id: ossrh
2020-01-04T17:14:29.9529183Z   maven_goals_phases: clean deploy
2020-01-04T17:14:29.9529836Z env:
2020-01-04T17:14:29.9530482Z   JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.232/x64
2020-01-04T17:14:29.9531197Z   JAVA_HOME_8.0.232_x64: /opt/hostedtoolcache/jdk/8.0.232/x64
2020-01-04T17:14:29.9531900Z ##[endgroup]
2020-01-04T17:14:30.0022742Z Importing GPG keyâ€¦
2020-01-04T17:14:30.1524626Z gpg: directory '/home/runner/.gnupg' created
2020-01-04T17:14:30.1528872Z gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
2020-01-04T17:14:30.1749845Z gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
2020-01-04T17:14:30.1752912Z gpg: key 34BD149B2C1C1354: public key "Nacho (GPG key for signing Maven packages) <***@gmail.com>" imported
2020-01-04T17:14:30.2400414Z gpg: key 34BD149B2C1C1354: secret key imported
2020-01-04T17:14:30.2407096Z Deploying the Maven projectâ€¦
2020-01-04T17:14:30.2415822Z gpg: Total number processed: 1
2020-01-04T17:14:30.2416784Z gpg:               imported: 1
2020-01-04T17:14:30.2417432Z gpg:       secret keys read: 1
2020-01-04T17:14:30.2418747Z gpg:   secret keys imported: 1
2020-01-04T17:14:30.2461591Z child_process.js:660
2020-01-04T17:14:30.2462269Z     throw err;
2020-01-04T17:14:30.2462874Z     ^
2020-01-04T17:14:30.2463202Z 
2020-01-04T17:14:30.2464026Z Error: spawnSync /bin/sh ENOENT
2020-01-04T17:14:30.2464717Z     at Object.spawnSync (internal/child_process.js:1041:20)
2020-01-04T17:14:30.2465498Z     at spawnSync (child_process.js:607:24)
2020-01-04T17:14:30.2466793Z     at execSync (child_process.js:652:15)
2020-01-04T17:14:30.2468278Z     at run (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/index.js:23:9)
2020-01-04T17:14:30.2469517Z     at runAction (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/index.js:82:2)
2020-01-04T17:14:30.2470747Z     at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/index.js:88:1)
2020-01-04T17:14:30.2471591Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-01-04T17:14:30.2472395Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-01-04T17:14:30.2473197Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2020-01-04T17:14:30.2473998Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
2020-01-04T17:14:30.2474954Z   errno: 'ENOENT',
2020-01-04T17:14:30.2475745Z   code: 'ENOENT',
2020-01-04T17:14:30.2476902Z   syscall: 'spawnSync /bin/sh',
2020-01-04T17:14:30.2478069Z   path: '/bin/sh',
2020-01-04T17:14:30.2478727Z   spawnargs: [
2020-01-04T17:14:30.2479545Z     '-c',
2020-01-04T17:14:30.2480737Z     'mvn clean deploy --batch-mode --activate-profiles deploy --settings /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/settings.xml -DskipTests'
2020-01-04T17:14:30.2481615Z   ],
2020-01-04T17:14:30.2482245Z   error: [Circular],
2020-01-04T17:14:30.2482881Z   status: null,
2020-01-04T17:14:30.2485217Z   signal: null,
2020-01-04T17:14:30.2486902Z   output: null,
2020-01-04T17:14:30.2487560Z   pid: 3026,
2020-01-04T17:14:30.2488174Z   stdout: null,
2020-01-04T17:14:30.2488771Z   stderr: null
2020-01-04T17:14:30.2489379Z }
2020-01-04T17:14:30.2493258Z ##[error]Node run failed with exit code 1
2020-01-04T17:14:30.2563296Z Cleaning up orphan processes

**Comment by samuelmeuli** [comment]
Thanks for reporting!

This might be an issue with the action's default value for `execSync`'s `cwd` parameter. Would you mind running your workflow again with v1.3.1?

**Comment by imedina** [comment]
Sure, no problem!

All good now :-)    thanks!
