### ISSUE TITLE
no valid OpenPGP data found

### ISSUE THREAD

**Issue by lwydyby** [samuelmeuli/action-maven-publish#9]
Error: Command failed: gpg --import --batch /Users/runner/runners/2.163.1/work/_actions/samuelmeuli/action-maven-publish/v1.3.1/private-key.txt
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/Users/runner/runners/2.163.1/work/_actions/samuelmeuli/action-maven-publish/v1.3.1/index.js:23:9)
    at runAction (/Users/runner/runners/2.163.1/work/_actions/samuelmeuli/action-maven-publish/v1.3.1/index.js:74:3)
    at Object.<anonymous> (/Users/runner/runners/2.163.1/work/_actions/samuelmeuli/action-maven-publish/v1.3.1/index.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 2638,
  stdout: null,
  stderr: null
}

**Comment by lwydyby** [comment]
https://github.com/lwydyby/wwmxd-log/blob/fe0c666092ee9c7f1585975c20804dbe98f4cf77/wwmxd-log/pom.xml

**Comment by ksclarke** [comment]
@lwydyby What was the solution here? I've got this setup on another project where it works but am getting this error on a new project setup. I figure it's something I'm forgetting, but ??

_EDIT:_ Since I figured out my problem, I'll leave a note for others as absent minded as myself: You need to put the whole GPG secret key in the project's Secrets (not just the secret key's ID). I did that right on my first project but apparently forgot it on the second one. I guess on the second project I thought it'd magically pull it from the GPG key associated with my account... nope.
